# config/mission_params.yaml
# Configuration parameters for SITL mission management nodes

power_monitor:
  ros__parameters:
    safety_margin: 0.25          # 25% safety margin for RTL calculation
    average_return_speed: 12.0   # Average return speed in m/s
    battery_check_interval: 5.0  # Check battery every 5 seconds
    min_battery_voltage: 14.0    # Minimum acceptable battery voltage
    rtl_triggered_threshold: 0.20 # Trigger RTL at 20% battery (lowered for SITL)
    battery_capacity_mah: 5000.0  # Battery capacity
    min_current_threshold: 0.1    # Minimum current threshold
    current_averaging_window: 10  # Current averaging window
    home_position_timeout: 30.0   # Home position timeout
    sitl_mode: true              # Enable SITL mode
    command_cooldown: 5.0        # Seconds between command attempts
    max_command_retries: 3

fault_detector:
  ros__parameters:
    gps_timeout: 15.0           # GPS timeout in seconds
    min_satellites: 6           # Minimum satellites for good fix
    min_fix_type: 3             # Minimum GPS fix type (3 = 3D fix)
    check_interval: 5.0         # System health check interval
    estimator_timeout: 20.0     # Increased for SITL
    startup_grace_period: 15.0  # Grace period for startup
    sitl_mode: true            # Enable SITL mode
    emergency_command_cooldown: 5.0    
    gps_failure_count_threshold: 3 

mission_supervisor:
  ros__parameters:
    heartbeat_timeout: 30.0     # MAVROS heartbeat timeout
    telemetry_timeout: 20.0     # Increased telemetry timeout for SITL
    mission_timeout: 3600.0     # Maximum mission duration (1 hour)
    check_interval: 3.0         # Supervision check interval
    critical_battery_threshold: 5.0  # Real critical battery level
    startup_grace_period: 15.0  # Grace period for startup
    command_cooldown: 5.0
